### ISSUE TITLE
1.2.0正式版已經上線

### ISSUE THREAD

**Issue by a19901201** [GMYXDS/rustdesk-api-server#1]
基於這個版本
會朝向哪些方向改動?
或許我能協助部分PR
但總體流程希望可以有個預期目標
這樣更好協作

**Comment by GMYXDS** [comment]
感谢，这个项目目前有2个版本，分别是基于rustdesk 1.9.0及以前，和rustdesk1.2.0

由于官方1.2.0版本还是开发状态，不是很稳定，不建议使用，所以1.2.0版本的api只是写出来尝尝鲜。等官方发布了稳定版本后会跟进

主要在维护1.9.0版本。后续开发希望加上以下功能
1。对sqlite数据库的支持
2。对docker的支持
3。系统后台的设计
4。其他

对于我来说，因为目前来说够用，也比较忙。所以暂时没有时间去完善。上面都是呼声比较高的功能，如果有能力欢迎pr

**Comment by GMYXDS** [comment]
刚刚看见1.2.0发布了 ,关于api server所发展的方向和1.9.0旧版一样，如果你有什么其他好的想法也欢迎讨论

**Comment by yunxilyf** [comment]
我这运行老提示这个错误，数据库密码用户名都是对的，也报错连接失败
Application Rustdesk Api Sever V2 cannot handle your request

**Comment by GMYXDS** [comment]
> 我这运行老提示这个错误，数据库密码用户名都是对的，也报错连接失败 Application Rustdesk Api Sever V2 cannot handle your request

新开个isuue，打开debug，把输出日志粘贴出来看看

**Comment by wanghanming** [comment]
> > 我这运行老提示这个错误，数据库密码用户名都是对的，也报错连接失败 Application Rustdesk Api Sever V2 cannot handle your request
> 
> 新开个isuue，打开debug，把输出日志粘贴出来看看

v2的问题已经发现了 ，是1.20 回复的数据格式不一致。
获取的api地址也不一致
 rows = await app.ctx.poolmysqlasync.fetchall(sql, res['uid'])
        for row in rows:
            peers.append({
                "id": row['client_id'],
                "username": row['username'],
                "hostname": row['hostname'],
                "alias": row['alias'],
                "platform": row['platform'],
                "tags": json_tools.loads(row['tags']),
 
            })
            # "forceAlwaysRelay": row['forceAlwaysRelay'],
            # "rdpPort": row['rdpPort'],
            # "rdpUsername": row['rdpUsername']
 
原文链接：https://blog.csdn.net/qq_37162503/article/details/134184454

**Comment by wanghanming** [comment]
> > 我这运行老提示这个错误，数据库密码用户名都是对的，也报错连接失败 Application Rustdesk Api Sever V2 cannot handle your request
> 
> 新开个isuue，打开debug，把输出日志粘贴出来看看



> 我这运行老提示这个错误，数据库密码用户名都是对的，也报错连接失败 Application Rustdesk Api Sever V2 cannot handle your request

数据库建议使用 mysql 8.0 以上的
