### ISSUE TITLE
When authorized does not connect to the remote table 1.2

### ISSUE THREAD

**Issue by vaalimusic** [GMYXDS/rustdesk-api-server#3]
Connection timeout in version 1.2 only when I'm logged in. What could be the problem?

**Comment by GMYXDS** [comment]
provide more details，let me can help you.
Like screenshots，logs output frome backends.

**Comment by vaalimusic** [comment]
Thanks for answering. Unfortunately, I did not find how to view the logs of the server part of RustDesk, but I noticed an interesting feature. If I am authorized in the address book, I connect to remote computers for much longer, and for some it takes so long that the connection is reset referring to a timeout. The fact that I am authorized in the address book can somehow affect the connection speed? I'll update the post once I figure out the logs.


(Updated) Unfortunately, it still does not connect, I checked everything. If the encryption key in the settings is removed, it connects immediately. But not with him.

**Comment by GMYXDS** [comment]
I will check my code later. the rustdesk server just publish 1.2.0 offical last few days.
TBH, what i do is to implement a function that can get rustdesk accounts from your own sever.
It shouldn't affect your server's connection rate. The connection rate that can affect your server is only the condition of your transit server, such as bandwidth. . .

like what you said,`If the encryption key in the settings is removed, it connects immediately` the `encryption key` is rustdesk sever's job , it's has no relation to the rustdesk api server.

**Comment by vaalimusic** [comment]
Thanks for the answer. I can't run the flutter version from source to inspect the code, but the official web pro version has no such problems. I suspect it is the flatter client that has some pitfalls, I installed some other api from other people and the problems are the same, even on the local network. It would be cool to solve this problem.

**Comment by zhangbo8418** [comment]
> I will check my code later. the rustdesk server just publish 1.2.0 offical last few days. TBH, what i do is to implement a function that can get rustdesk accounts from your own sever. It shouldn't affect your server's connection rate. The connection rate that can affect your server is only the condition of your transit server, such as bandwidth. . .
> 
> like what you said,`If the encryption key in the settings is removed, it connects immediately` the `encryption key` is rustdesk sever's job , it's has no relation to the rustdesk api server.

It is obvious that the data sent when initiating a connection from the client app in a logged-in state versus not logged in would be different.
